### ISSUE TITLE
Broken Assignments

### ISSUE THREAD

**Issue by AlerGames** [EvanNotFound/omnivox-optimizer#1]
Heyhey! I think the assignments tab is broken. Whenever I click on it, the page becomes blank. 
![image](https://github.com/user-attachments/assets/4fc4d728-2d22-40f4-ba70-d8106eea29c8)
![image](https://github.com/user-attachments/assets/2d33217f-b9d6-49d8-80a6-a591da4bb9cb)

**Comment by EvanNotFound** [comment]
fixed in https://github.com/EvanNotFound/omnivox-optimizer/releases/tag/v1.3.9

please click on the installation link https://github.com/evannotfound/omnivox-optimizer/releases/latest/download/omnivox-optimizer.user.js to update to the latest version

**Comment by AlerGames** [comment]
You're the man
