### ISSUE TITLE
Opening a link on Léa's documents redirects to a blank page

### ISSUE THREAD

**Issue by Youcxf** [EvanNotFound/omnivox-optimizer#2]
I tried to open a link to the WebWORK page assigned by my teacher but the redirection does not work. Though, documents and PDFs work. I've tried copying the link and opening in a new tab. 

I think it may be because it is trying to use the visualize document method which doesn't work with links maybe? (not sure)

![Capture d'écran 2024-11-22 214220](https://github.com/user-attachments/assets/cc3438c0-1c7f-42a6-88f2-e791802992df)
![image](https://github.com/user-attachments/assets/e4a1066f-58d5-4902-b825-a3a05c218dc6)
![image](https://github.com/user-attachments/assets/2726062e-48ea-4835-9f7f-99700f6c9f9a)

**Comment by EvanNotFound** [comment]
fixed in https://github.com/EvanNotFound/omnivox-optimizer/releases/tag/v1.3.11

please click on the installation link https://github.com/evannotfound/omnivox-optimizer/releases/latest/download/omnivox-optimizer.user.js to update to the latest version

**Comment by Youcxf** [comment]
tysm keep going i really like the project!
